### ISSUE TITLE
Migrate `azure/notebooks/HPO-SKLearn.ipynb` to deployment docs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cloud-ml-examples#216]
Migrate [azure/notebooks/HPO-SKLearn.ipynb](../blob/main/azure/notebooks/HPO-SKLearn.ipynb) to deployment docs.

See https://github.com/rapidsai/cloud-ml-examples/issues/203#issuecomment-1410349915 for detailed migration instructions.

```[tasklist]
### Tasks
- [ ] Decide if notebook should be migrated and add "migrate: X" label (if no also close this issue)
- [ ] Test if notebook works
- [ ] Fix up anything that needs changing
- [ ] Ensure notebook has good title, description and metadata tags in the first cell
- [ ] Replace deployment instructions with links to docs pages
- [ ] Copy notebook into a new folder into deployment docs examples
- [ ] Copy any supporting files to the folder
- [ ] Add notebook to examples toctree
- [ ] Make PR to deployment docs repo
```

**Comment by skirui-source** [comment]
@jacobtomlinson

 I don't think we should migrate  [sklearn_train_notebook](https://github.com/rapidsai/cloud-ml-examples/blob/main/azure/notebooks/Train-SKLearn.ipynb), [sklearn_hpo_notebook ](https://github.com/rapidsai/cloud-ml-examples/blob/main/azure/notebooks/HPO-SKLearn.ipynb), and [rapids_train_notebook](https://github.com/rapidsai/cloud-ml-examples/blob/main/azure/notebooks/Train-RAPIDS.ipynb),  seeing as there is MAJOR overlap with the [rapids_hpo_notebook](https://github.com/rapidsai/cloud-ml-examples/blob/main/azure/notebooks/HPO-RAPIDS.ipynb) (covers training + hyperparameters tuning  in AzureML)

I am working on consolidating them in https://github.com/rapidsai/deployment/pull/192


Lmk your thoughts?

**Comment by jacobtomlinson** [comment]
Fine with me, thanks @skirui-source
