### ISSUE TITLE
Migrate `databricks/notebooks/rapids_airline_hyperopt.ipynb` to deployment docs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cloud-ml-examples#218]
Migrate [databricks/notebooks/rapids_airline_hyperopt.ipynb](../blob/main/databricks/notebooks/rapids_airline_hyperopt.ipynb) to deployment docs.

See https://github.com/rapidsai/cloud-ml-examples/issues/203#issuecomment-1410349915 for detailed migration instructions.

```[tasklist]
### Tasks
- [x] Decide if notebook should be migrated and add "migrate: X" label (if no also close this issue)
- [ ] Test if notebook works
- [ ] Fix up anything that needs changing
- [ ] Ensure notebook has good title, description and metadata tags in the first cell
- [ ] Replace deployment instructions with links to docs pages
- [ ] Copy notebook into a new folder into deployment docs examples
- [ ] Copy any supporting files to the folder
- [ ] Add notebook to examples toctree
- [ ] Make PR to deployment docs repo
```

**Comment by jacobtomlinson** [comment]
@skirui-source is currently writing up some Databricks deployment instructions in https://github.com/rapidsai/deployment/issues/92.

This notebook doesn't have much about deployment in, so it would be great to add a little pre-amble about launching on Databricks and link to the page @skirui-source is working on.

**Comment by betatim** [comment]
I'll take a look at this
