### ISSUE TITLE
Migrate `databricks/notebooks/rapids_intro.ipynb` to deployment docs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cloud-ml-examples#219]
See https://github.com/rapidsai/cloud-ml-examples/issues/203#issuecomment-1410349915 for detailed migration instructions.

```[tasklist]
### Tasks
- [x] Decide if notebook should be migrated and add "migrate: X" label (if no also close this issue)
- [ ] Test if notebook works
- [ ] Fix up anything that needs changing
- [ ] Ensure notebook has good title, description and metadata tags in the first cell
- [ ] Replace deployment instructions with links to docs pages
- [ ] Copy notebook into a new folder into deployment docs examples
- [ ] Copy any supporting files to the folder
- [ ] Add notebook to examples toctree
- [ ] Make PR to deployment docs repo

```

**Comment by jacobtomlinson** [comment]
This notebook doesn't really have anything to do with deployment or Databricks. I don't think we should migrate it.
