### ISSUE TITLE
Migrate `aws/rapids_sagemaker_higgs/sagemaker_rapids_higgs.ipynb` to deployment docs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cloud-ml-examples#231]
Migrate [aws/rapids_sagemaker_higgs/sagemaker_rapids_higgs.ipynb](../blob/main/aws/rapids_sagemaker_higgs/sagemaker_rapids_higgs.ipynb) to deployment docs.

See https://github.com/rapidsai/cloud-ml-examples/issues/203#issuecomment-1410349915 for detailed migration instructions.

```[tasklist]
### Tasks
- [x] Decide if notebook should be migrated and add "migrate: X" label (if no also close this issue)
- [x] Test if notebook works
- [x] Fix up anything that needs changing
- [x] Ensure notebook has good title, description and metadata tags in the first cell
- [x] Replace deployment instructions with links to docs pages
- [x] Copy notebook into a new folder into deployment docs examples
- [x] Copy any supporting files to the folder
- [x] Add notebook to examples toctree
- [x] Make PR to deployment docs repo
```

**Comment by jacobtomlinson** [comment]
I already migrated a version of this notebook for testing in https://github.com/rapidsai/deployment/pull/108. Need to go back over the checklist and ensure it is done correctly though.

**Comment by jacobtomlinson** [comment]
I ran through the instructions and the diff with what we have from https://github.com/rapidsai/deployment/pull/108 came out the same so this is done.

**Comment by jacobtomlinson** [comment]
Looks like https://github.com/rapidsai/cloud-ml-examples/pull/204 makes a bunch of changes to that notebook so reopening this for migration.
