### ISSUE TITLE
Migrate `aws/rapids_ec2_mnmg.ipynb` to deployment docs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cloud-ml-examples#233]
Migrate [aws/rapids_ec2_mnmg.ipynb](../blob/main/aws/rapids_ec2_mnmg.ipynb) to deployment docs.

See https://github.com/rapidsai/cloud-ml-examples/issues/203#issuecomment-1410349915 for detailed migration instructions.

```[tasklist]
### Tasks
- [x] Decide if notebook should be migrated and add "migrate: X" label (if no also close this issue)
- [x] Test if notebook works
- [x] Fix up anything that needs changing
- [x] Ensure notebook has good title, description and metadata tags in the first cell
- [x] Replace deployment instructions with links to docs pages
- [x] Copy notebook into a new folder into deployment docs examples
- [x] Copy any supporting files to the folder
- [x] Add notebook to examples toctree
- [x] Make PR to deployment docs repo
```

**Comment by jacobtomlinson** [comment]
The top part of this notebook up until "Client Setup" should be migrated to a docs page on starting a MNMG EC2 cluster. This will be very similar to the [Azure VM Cluster (with Dask)](https://github.com/rapidsai/deployment/blob/main/source/cloud/azure/azure-vm-multi.md) page but for AWS.

Then in the notebook that whole section could be collapsed to a reference to the docs page.
