### ISSUE TITLE
Migrate `aws/rapids_sagemaker_hpo_extended.ipynb` to deployment docs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cloud-ml-examples#237]
Migrate [aws/rapids_sagemaker_hpo_extended.ipynb](../blob/main/aws/rapids_sagemaker_hpo_extended.ipynb) to deployment docs.

See https://github.com/rapidsai/cloud-ml-examples/issues/203#issuecomment-1410349915 for detailed migration instructions.

```[tasklist]
### Tasks
- [x] Decide if notebook should be migrated and add "migrate: X" label (if no also close this issue)
- [x] Test if notebook works
- [x] Fix up anything that needs changing
- [x] Ensure notebook has good title, description and metadata tags in the first cell
- [x] Replace deployment instructions with links to docs pages
- [x] Copy notebook into a new folder into deployment docs examples
- [x] Copy any supporting files to the folder
- [x] Add notebook to examples toctree
- [x] Make PR to deployment docs repo
```
